package hibernateData;
// Generated 8 mars 2018 16:41:00 by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int authorId;
     private String authorLastname;
     private String authorFirstname;

    public Author() {
    }

	
    public Author(int authorId) {
        this.authorId = authorId;
    }
    public Author(int authorId, String authorLastname, String authorFirstname) {
       this.authorId = authorId;
       this.authorLastname = authorLastname;
       this.authorFirstname = authorFirstname;
    }
   
    public int getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(int authorId) {
        this.authorId = authorId;
    }
    public String getAuthorLastname() {
        return this.authorLastname;
    }
    
    public void setAuthorLastname(String authorLastname) {
        this.authorLastname = authorLastname;
    }
    public String getAuthorFirstname() {
        return this.authorFirstname;
    }
    
    public void setAuthorFirstname(String authorFirstname) {
        this.authorFirstname = authorFirstname;
    }




}


